### ISSUE TITLE
Deploy dev builds to PyPI

### ISSUE THREAD

**Issue by Jlrine2** [ASFHyP3/hyp3-sdk#103]
Currently the only way to run the code in the develop branch of this repo is to install it locally, it would be nice to have dev versions pushed to PyPi so that they can be pip installed.

**Comment by jhkennedy** [comment]
I'm not sure this is needed; you can pip install this repo at any tag/commit/branch

```
python -m pip install git+https://github.comASFHyP3/hyp3-sdk.git@[REF]
```
