### ISSUE TITLE
Consider removing 'Found zero jobs' UserWarning

### ISSUE THREAD

**Issue by Alex-Lewandowski** [ASFHyP3/hyp3-sdk#117]
**Describe the bug**
This isn't really a bug, but it's not a feature request either. When calling find_jobs on a project containing no jobs matching the passed args, the 'Found zero jobs' UserWarning is raised. 

**To Reproduce**
1. Create a project of RTC jobs
2. hyp3.find_jobs(name=project_name, job_type='INSAR_GAMMA')
3. See warning

**Expected behavior**
I would prefer this to be handled like a failed regex search, return none (or maybe an empty Batch)

**Additional context**
I understand if you have reasons to keep the warning. For my use case, suppressing it works just fine.

**Comment by jhkennedy** [comment]
Right now, it will work like a failed regex in that we do return an empty Batch, we just also warn. The warning is/was intended to help users who wouldn't be expecting a failed search to know it immediately, but there definitely are use cases where you might not care and the warning is annoying. 

Definitely worth revisiting -- possible options:
1. Remove the warning
2. option to suppress warning
3. option to turn on the warning

I think 3 is likely to result in the option not being used, so I'd advocate for 1 or 2 and am leaning slightly towards 1...
