### ISSUE TITLE
add log decibel scaling to `scale` options

### ISSUE THREAD

**Issue by Scartography** [ASFHyP3/hyp3-sdk#165]
* simply 10*log(vv/vh) to the result will do the trick

**Comment by jhkennedy** [comment]
@Scartography thanks for the suggestion! We have it on our backlog, but don't have a timeline currently. Would you mind sharing a few sentences on why this would help you, so I can help prioritize it?

**Comment by jhkennedy** [comment]
@Scartography Thanks! 

We do also provide the `asf_tools` Python package which has a [`raster.convert_scale`](https://hyp3-docs.asf.alaska.edu/tools/asf_tools_api/#asf_tools.raster.convert_scale) to convert between db, amp, and power. But it would be nice to provide it directly.

**Comment by jhkennedy** [comment]
@Scartography as of HyP3 SDK v1.7.2 (#179), products can be requested in Decibel scale. Sorry that it took so long to get to it!
