### ISSUE TITLE
Better error message when user has not accepted the ASF EULA

### ISSUE THREAD

**Issue by jhkennedy** [ASFHyP3/hyp3-sdk#170]
When a user's Earthdata Login account credentials are valid, but they try and access HyP3 before accepting ASF's EULA and/or specifying a study area, the SDK raises an `AuthenticationError` just like if invalid credentials were invalid. It would be nice to prompt users to accept the EULA instead, or at least at it as a possible reason to the `AuthenticationError` message.

TODO:

- [x] Finish steps for a HyP3 SDK release since merging https://github.com/ASFHyP3/hyp3-sdk/pull/201
- [x] Fix bug: https://github.com/ASFHyP3/hyp3-sdk/issues/170#issuecomment-1481736375
- [x] Test the changes with version 2.0.1 and a new Earthdata user:
    - [x] Using credentials from `.netrc` produces correct error message when Study Area not selected
    - [x] Passing credentials manually produces correct error message when Study Area not selected
    - [x] Using credentials from `.netrc` produces correct error message when EULA not accepted
    - [x] Passing credentials manually produces correct error message when EULA not accepted
    - [x] Using credentials from `.netrc` works after Study Area has been selected and EULA accepted
    - [x] Passing credentials manually works after Study Area has been selected and EULA accepted
    - [x] Using false credentials from `.netrc` produces correct error message
    - [x] Passing false credentials manually produces correct error message
- [x] Finish steps for SDK release since merging 2.0.1

**Comment by kevinxmorales** [comment]
I would like to work on this issue. After some initial investigation, the response sent back when the EULA is not accepted contains a url with some query params that could be useful for making a better error message,

**Comment by jhkennedy** [comment]
@kevinxmorales that'd be great! I'd be happy to review a PR (at any stage).

**Comment by jtherrmann** [comment]
I just realized that the improved error messages will not be shown if attempting to login from `.netrc` file. We should fix that.
