### ISSUE TITLE
submit_insar_job(looks="5x1")

### ISSUE THREAD

**Issue by ZGHHGZ** [ASFHyP3/hyp3-sdk#177]
I'm looking forward to adding looks="5x1" in submit_insar_job()

**Comment by jhkennedy** [comment]
@ZGHHGZ providing 5x1 InSAR is on our backlog, and we hope to get to it soon but have no timeline yet. I'll close this issue once it's available via the SDK.

**Comment by ZGHHGZ** [comment]
Hello, will it probably be updated this year?

**Comment by ZGHHGZ** [comment]
> @ZGHHGZ providing 5x1 InSAR is on our backlog, and we hope to get to it soon but have no timeline yet. I'll close this issue once it's available via the SDK.

Hello, will it probably be updated this year?

**Comment by jhkennedy** [comment]
While 5x1 is still not available for our GAMMA-based InSAR products, our ISCE2-based burst products do offer `looks='5x1'` now:
https://hyp3-docs.asf.alaska.edu/using/sdk_api/#hyp3_sdk.HyP3.prepare_insar_isce_burst_job

@ZGHHGZ does that meet your needs?
