### ISSUE TITLE
asf_search should offer persistent sessions to the ASF search APIs

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-sdk#80]
Currently a new HTTP connection is made each time `asf_search.get_metadata()` or `asf_search.get_neighbors()` is called.  Allowing the use of a persistent session could improve response times when making repeated queries.

**Comment by jhkennedy** [comment]
asf_search subpackage was depreciated and removed from the `hyp3_sdk`. Closing.
