### ISSUE TITLE
Error requesting granule when including a long name for the job.

### ISSUE THREAD

**Issue by rbavery** [ASFHyP3/hyp3-sdk#81]
**Describe the bug**
I am trying to request the following granule

`'S1A_IW_GRDH_1SDV_20191231T040931_20191231T040956_030587_038102_0C49'`

With this code

```python
from hyp3_sdk import HyP3
hyp3 = HyP3(username='user', password='pass')
granule = 'S1A_IW_GRDH_1SDV_20191231T040931_20191231T040956_030587_038102_0C49'
name = 'Kisangani S1A_IW_GRDH_1SDV_20191231T040931_20191231T040956_030587_038102_0C49'
hyp3.submit_rtc_job(granule=granule, name=name)
```

And I get this error.

```python
HyP3Error: 400 Client Error: Bad Request for url: https://hyp3-api.asf.alaska.edu/jobs
```

If I remove the `name` argument it works. I'm not sure why this is breaking since `name` is a valid str. Is the `name` too long? When I shorten it, the job submission works.

**To Reproduce**
```python
from hyp3_sdk import HyP3
hyp3 = HyP3(username='user', password='pass')
granule = 'S1A_IW_GRDH_1SDV_20191231T040931_20191231T040956_030587_038102_0C49'
name = 'Kisangani S1A_IW_GRDH_1SDV_20191231T040931_20191231T040956_030587_038102_0C49'
hyp3.submit_rtc_job(granule=granule, name=name)
```

**Expected behavior**
Job is submitted.

**Comment by asjohnston-asf** [comment]
Thanks for the report!  The name field is currently limited to 20 characters.

The HyP3 SDK doesn't currently expose detailed messages for HTTP 400 errors, we have #69 open to track that as a related issue.
